### ISSUE TITLE
Some error occurs while running the demo.

### ISSUE THREAD

**Issue by dianzai** [pmj110119/YOLOX_deepsort_tracker#10]
Traceback (most recent call last):
  File "demo.py", line 52, in <module>
    track_cap(args.path)
  File "demo.py", line 34, in track_cap
    image,_ = tracker.update(im)
  File "G:\YOLOX_deepsort_tracker-master\tracker.py", line 27, in update
    info = self.detector.detect(image, visual=False)
  File "G:\YOLOX_deepsort_tracker-master\detector.py", line 55, in detect
    info['boxes'] = outputs[:, 0:4]/ratio
TypeError: 'NoneType' object is not subscriptable

**Comment by pmj110119** [comment]
Hello, I'm sorry for the late reply.

It seems that this bug will appear when YOLOX predicted nothing.

I think I have fixed it, thanks for your report very much！
