### ISSUE TITLE
A bug

### ISSUE THREAD

**Issue by johnwingit** [pmj110119/YOLOX_deepsort_tracker#12]
Traceback (most recent call last):
  File "/home/下载/Pytorch_YOLOx_Deepsort-main/track.py", line 113, in <module>
    vdo_trk.run()
  File "/home//下载/Pytorch_YOLOx_Deepsort-main/track.py", line 64, in run
    info = self.detector.detect(im, visual=False)
  File "/home/下载/Pytorch_YOLOx_Deepsort-main/YOLOX/detector.py", line 53, in detect
    info['boxes'] = outputs[:, 0:4]/ratio
TypeError: 'NoneType' object is not subscriptable

**Comment by charmin161** [comment]
same problem. have you fixed it?

**Comment by charmin161** [comment]
the author has fixed it at the newest code
