### ISSUE TITLE
TypeError: load() missing 1 required positional argument: 'Loader'

### ISSUE THREAD

**Issue by zkailinzhang** [pmj110119/YOLOX_deepsort_tracker#13]
(py37) :YOLOX_deepsort_tracker$ python demo.py --path=xx.mp4 
Traceback (most recent call last):
  File "demo.py", line 57, in <module>
    track_images(args.path)
  File "demo.py", line 10, in track_images
    tracker = Tracker(model='yolox-s', ckpt='weights/yolox_s.pth',filter_class=['truck','person','car'])
  File "YOLOX_deepsort_tracker/tracker.py", line 18, in __init__
    cfg.merge_from_file("deep_sort/configs/deep_sort.yaml")
  File "YOLOX_deepsort_tracker/deep_sort/utils/parser.py", line 23, in merge_from_file
    self.update(yaml.load(fo.read()))
TypeError: load() missing 1 required positional argument: 'Loader'

**Comment by namtranase** [comment]
Try this:
```python
        with torch.no_grad():
            outputs = self.model(img)
            outputs = postprocess(
                outputs, self.exp.num_classes, self.exp.test_conf, self.exp.nmsthre  # TODO:用户可更改
            )
            if outputs[0] is not None:
                outputs = outputs[0].cpu().numpy()
```
