### ISSUE TITLE
load() missing 1 required positional argument: 'Loader'

### ISSUE THREAD

**Issue by Kerwin0621** [pmj110119/YOLOX_deepsort_tracker#16]
Traceback (most recent call last):
  File "/home/kerwin/KeTrack/demo.py", line 59, in <module>
    track_images(args.path)
  File "/home/kerwin/KeTrack/demo.py", line 10, in track_images
    tracker = Tracker(model='yolox-s', ckpt='weights/yolox_s.pth',filter_class=['person'])
  File "/home/kerwin/KeTrack/tracker.py", line 18, in __init__
    cfg.merge_from_file("deep_sort/configs/deep_sort.yaml")
  File "/home/kerwin/KeTrack/deep_sort/utils/parser.py", line 23, in merge_from_file
    self.update(yaml.load(fo.read()))
TypeError: load() missing 1 required positional argument: 'Loader'

**Comment by winner-4** [comment]
Hello, I also encountered the same problem as you. Have you solved it?

**Comment by Anoue** [comment]
1.slef.update(yaml.load(fo.read(),Loader=yaml.FullLoader))
2.self.update(yaml.safe_load(fo.read()))
3.self.update(yaml.load(fo.read(), Loader=yaml.CLoader))
Choose one from three
